const App = {
  graphCache: null,      // stores all figurative language nodes (metaphor/simile/aphorism)
  sentenceCache: null,   // stores all paragraph/sentence nodes + their tokenized words
  activeWord: null       // remembers what word the user clicked last (used for graph focus)
};

// This runs once the HTML generated by XSLT has fully loaded into the browser
document.addEventListener("DOMContentLoaded", () => {

  // scan DOM and build model for figurative language nodes
  cacheDocument();
  //  scan DOM and build model for sentences
  cacheSentences();
  // put clicks on buttons
  initViewButtons();
  // put clicks on metaphor/simile/aphorism nodes 
  initMetaphorClicks();
});


/* Figurative Language cache of all <metaphor>, <simile>, <aphorism> elements in the DOM*/
// so we can quickly search, and compute relationships later (instead of querying DOM repeatedly)

function cacheDocument() {
  const items = document.querySelectorAll('metaphor, simile, aphorism');

  // Convert NodeList → Array and map into structured JS objects
  App.graphCache = Array.from(items).map(el => ({
    el,  // store the actual DOM node (important for clicking + navigation)

    // normalizes
    type: el.tagName.toLowerCase(),
    // store the dataset attributes
    sentenceId: el.dataset.sentence,
    // convert text inside this node into an array of words (indexed, navigable for JS)
    words: tokenize(el.textContent)

  }));

}


/* This next bit is for the <p> nodes we created in xslt, <p> = sentences here, it indexs them and says whether they are figurative language or not*/
function cacheSentences() {

  // Select all <p> and map with text
  const sentences = document.querySelectorAll('p');
  App.sentenceCache = Array.from(sentences).map(p => {
    const words = tokenize(p.textContent);

    // check if sentence contains ANY figurative language nodes inside it
    const hasFigurative =
      p.querySelector('metaphor, simile, aphorism') !== null;

    return {

      el: p,              // store node/location for scrolling/navigation
      words,             // tokenized version of sentence (for pulling later)
      hasFigurative      // flag used for styling in UI

    };

  });

}



// Convert raw text into clean word list for analysis
function tokenize(text) {
  //  words removed to improve graph
  const stopwords = new Set([
    "the","and","is","in","of","a","to","but","with","for","on","into","he","who",
    "those","him","her","when","his","them","here","they","all","you","has","only",
    "that","it","can","was","if","my","there","as","i","or","this","have","had",
    "been","are","were","be","by","at","an","so","do","does","did","not"
  ]);

  return text
    .toLowerCase()              // normalize
    .replace(/[^a-z\s]/g, '')   // find anything that is not a lowercase letter (a–z) or whitespace (\s), and delete
    .split(/\s+/)               // split into individual words for graph
    .filter(w => w && !stopwords.has(w)); // remove empty + stopwords above

}


//View is for CSS, Show one panel at a time (reading / analysis / metaphor view)
function showView(viewId) {

  // select all views, for each view, turn it off
  document.querySelectorAll('.view')
    .forEach(v => v.classList.remove('active'));

  // show selected view
  document.getElementById(viewId)
    .classList.add('active');

}



// Connect UI buttons to view switch
function initViewButtons() {

  document.getElementById("view-reading")
    .addEventListener("click", () => showView("reading-view"));

  document.getElementById("view-analysis")
    .addEventListener("click", () => showView("analysis-view"));

  document.getElementById("view-metaphor")
    .addEventListener("click", () => showView("metaphor-view"));

}




// When user clicks a figurative phrase, open analysis view for its sentence (it's content, el)
function initMetaphorClicks() {

  document.querySelectorAll('metaphor, simile, aphorism')
    .forEach(el => {

      el.addEventListener("click", () => {

        openAnalysis(el);

      });

    });

}


// When a figurative phrase is clicked find its sentence, show the sentence, then build the word panel 

function openAnalysis(el) {
  // get sentence ID from dataset
  const sentenceId = el.dataset.sentence;
  // pull it
  const paragraph = document.getElementById(sentenceId);
  if (!paragraph) return; // safety check, makes sure it's figurative language
  // otherwise, switch to analysis panel
  showView("analysis-view");
  // show full sentence text in UI
  document.getElementById("analysis-sentence")
    .textContent = paragraph.textContent;
  // build clickable word buttons from sentence
  buildWordPanel(paragraph.textContent);
}



// Turn a sentence into clickable word buttons
// each word becomes an interaction trigger for the graph 

function buildWordPanel(text) {
  const words = tokenize(text);
  const panel = document.getElementById("word-panel");

  panel.innerHTML = ""; // clear old buttons each time you click a new word
  words.forEach(word => {

    const btn = document.createElement("button");
    btn.textContent = word;
    btn.addEventListener("click", () => {

      // store current selected word globally, to search for it globally later
      App.activeWord = word;
      // generate co-occurrence graph
      renderGraph(word);

    });

    panel.appendChild(btn); //shows button on page

  });

}



// Co-occurnece logic
//  Given a word: find all sentences containing it,
// then count which other words appear with it
function computeCooccurrence(word) {
  const counts = {};
  // loop through all sentences in dataset
  App.graphCache.forEach(entry => {
    // skip sentences that do not contain selected word
    if (!entry.words.includes(word)) return;
    // remove target word itself (we don’t count self-cooccurrence)
    const coWords = entry.words.filter(w => w !== word);
    const uniqueCoWords = new Set(coWords);
    uniqueCoWords.forEach(w => {
      if (!counts[w]) {
        counts[w] = {
          total: 0,     // frequency count
          types: new Set() // tracks word set diversity to see if it gets the bonus
        };
      }

      // increment occurrence count
      counts[w].total += 1;
      // track whether word came from metaphor/simile/aphorism context
      counts[w].types.add(entry.type);

    });

  });

  // convert into simple scores for graph ranking
  const result = {};
  Object.entries(counts).forEach(([w, data]) => {
    // boost words that appear across multiple figurative types by 2
    const typeBonus = data.types.size * 2;
    result[w] = data.total + typeBonus;

  });

  return result;

}



// Convert co-occurrence data into SVG bar
function renderGraph(word) {
  const data = computeCooccurrence(word);
  const svgNS = "http://www.w3.org/2000/svg";
  const svg = document.createElementNS(svgNS, "svg");

  // sort words by strength and keep top 10
  const entries = Object.entries(data)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10);

  const barSpacing = 100;
  const baseOffset = 50;
  const width = baseOffset + entries.length * barSpacing; //dynamically increases bar spacing based on number of entries, in case we change how many

  svg.setAttribute("width", width);
  svg.setAttribute("height", "300");

  entries.forEach(([w, count], i) => {//for each word count, index it for the bar
    // draw bar
    const rect = document.createElementNS(svgNS, "rect");
    rect.setAttribute("x", 50 + i * 100);
    rect.setAttribute("y", 250 - count * 20);
    rect.setAttribute("width", 20);
    rect.setAttribute("height", count * 20);

    // clicking a bar drills goes into  metaphor view
    rect.addEventListener("click", () => {
      openMetaphorView(word, w);
    });

    svg.appendChild(rect);

    // label under bar for text content
    const label = document.createElementNS(svgNS, "text");
    label.setAttribute("x", 50 + i * 100);
    label.setAttribute("y", 270);
    label.textContent = w;

    svg.appendChild(label);

  });

  // actually shows the graph
  const container = document.getElementById("graph-container");
  container.innerHTML = "";
  container.appendChild(svg);
}


//Metaphor View
// Show all sentences where both selected words co-occur
function openMetaphorView(wordA, wordB) {
  showView("metaphor-view");
  const results = App.sentenceCache.filter(entry =>
    entry.words.includes(wordA) && //sentences where both words show up
    entry.words.includes(wordB)
  );

  const container = document.getElementById("metaphor-results");
  container.innerHTML = "";
  results.forEach(entry => {
    const div = document.createElement("div"); //for each entry create it's own line

    // show original HTML of sentence
    div.innerHTML = entry.el.innerHTML;
    div.style.cursor = "pointer";
    div.style.marginBottom = "12px";
    div.style.padding = "8px";

    // highlight sentences containing figurative language
    if (entry.hasFigurative) {
      div.style.borderLeft = "4px solid gold";
      div.style.background = "rgba(255, 215, 0, 0.08)";
    }
    // clicking a result returns to reading view and scrolls to sentence
    div.addEventListener("click", () => {
      const el = entry.el;
      showView("reading-view");
      el.scrollIntoView({ behavior: "smooth", block: "center" });
      el.style.background = "yellow";

    });

    container.appendChild(div); 

  });

}
